//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_CART> TBL_CART { get; set; }
        public virtual DbSet<TBL_CARTSTATUS> TBL_CARTSTATUS { get; set; }
        public virtual DbSet<TBL_CATEGORY> TBL_CATEGORY { get; set; }
        public virtual DbSet<TBL_MEMBERROLE> TBL_MEMBERROLE { get; set; }
        public virtual DbSet<TBL_MEMBERS> TBL_MEMBERS { get; set; }
        public virtual DbSet<TBL_PRODUCT> TBL_PRODUCT { get; set; }
        public virtual DbSet<TBL_ROLES> TBL_ROLES { get; set; }
        public virtual DbSet<TBL_SHIPPINGDETAILS> TBL_SHIPPINGDETAILS { get; set; }
        public virtual DbSet<TBL_SLIDEIMAGE> TBL_SLIDEIMAGE { get; set; }
        public virtual DbSet<EMP_DETAILS_VIEW> EMP_DETAILS_VIEW { get; set; }
    }
}
