//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SLIDEIMAGE
    {
        public decimal SLIDEID { get; set; }
        public string SLIDTITLE { get; set; }
        public string SLIDEIMAGE { get; set; }
    }
}
