//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CART
    {
        public decimal CARTID { get; set; }
        public Nullable<decimal> PRODUCTID { get; set; }
        public Nullable<decimal> MEMBERID { get; set; }
        public Nullable<decimal> CARTSTATUSID { get; set; }
    
        public virtual TBL_PRODUCT TBL_PRODUCT { get; set; }
    }
}
