//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShoppingStore.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SHIPPINGDETAILS
    {
        public decimal SHIPPINGDETAILID { get; set; }
        public Nullable<decimal> MEMBERID { get; set; }
        public string ADDRESS { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string ZIPCODE { get; set; }
        public Nullable<decimal> ORDERID { get; set; }
        public Nullable<decimal> AMOUNTPAID { get; set; }
        public string PAYMENTTYPE { get; set; }
    
        public virtual TBL_MEMBERS TBL_MEMBERS { get; set; }
    }
}
